language: python

os:
  - linux
#  - osx # travis doesn't appear to support python on OSX as of right now...
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - 'nightly'
install:
  - pip install -e .
script:
  - ./test_all.sh
addons:
  apt:
    packages:
    - expect
